import Script from 'next/script';
import './index.css';
import localfont from 'next/font/local';

const monoFont = localfont(
  {
    src: "./fonts/UbuntuMono-Regular.ttf",
    display: "swap"
  }
);

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={monoFont.className}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>GPT Code Review</title>
      </head>
      <body className={monoFont.className}>{children}</body>
    </html>
  )
}
